DEF INPUT  PARAM icParam     AS CHAR NO-UNDO.
DEF INPUT  PARAM ihBuffer    AS HANDLE NO-UNDO.
DEF INPUT  PARAM icSessionId AS CHAR NO-UNDO.
DEF OUTPUT PARAM ocReturn    AS CHAR NO-UNDO.
DEF OUTPUT PARAM obOK        AS LOG NO-UNDO.

DEF VAR hLogoutTime AS HANDLE NO-UNDO.

FIND FIRST JBoxLoginSession WHERE JBoxLoginSession.cSessionId = icSessionId EXCLUSIVE-LOCK NO-WAIT NO-ERROR.
IF AVAIL JBoxLoginSession THEN DO:
  hLogoutTime = BUFFER JBoxLoginSession:HANDLE:BUFFER-FIELD("iLogoutTime") NO-ERROR.
  IF VALID-HANDLE(hLogoutTime) THEN
    hLogoutTime:BUFFER-VALUE = TIME.
END.
