  FIELD Hg LIKE VarGr.Hg VALIDATE ~
  FIELD Kolonne LIKE VarGr.Kolonne VALIDATE ~
  FIELD Kost_Proc LIKE VarGr.Kost_Proc VALIDATE ~
  FIELD MomsKod LIKE VarGr.MomsKod VALIDATE ~
  FIELD StoArt LIKE VarGr.StoArt VALIDATE ~
  FIELD Vg LIKE VarGr.Vg VALIDATE ~
  FIELD VgBeskr LIKE VarGr.VgBeskr VALIDATE  FORMAT "x(40)"~
  FIELD HgBeskr LIKE HuvGr.HgBeskr VALIDATE 
