  FIELD FilId LIKE VPIFilLogg.FilId VALIDATE ~
  FIELD Gradering LIKE VPIFilLogg.Gradering VALIDATE ~
  FIELD LinjeNr LIKE VPIFilLogg.LinjeNr VALIDATE ~
  FIELD Tekst LIKE VPIFilLogg.Tekst VALIDATE  FORMAT "X(180)"
