DELETE FROM anv-kod.
DELETE FROM avdeling.
DELETE FROM behandlingskode.
DELETE FROM farg.
DELETE FROM feilkode.
DELETE FROM Huvgr.
DELETE FROM Kasvaluta.
DELETE FROM Kjede.
DELETE FROM Kjededistrikt.
DELETE FROM kjedensbutikker.
DELETE FROM KjedeRegion.
DELETE FROM levbas.
DELETE FROM Levsort.
DELETE FROM LEvsant.
DELETE FROM moms.
DELETE FROM sasong.
DELETE FROM strtype.
DELETE FROM strtstr.
DELETE FROM valuta.
DELETE FROM vargr.
DELETE FROM vgkat.
