DEFINE VAR iButNr      AS INTEGER   NO-UNDO.
DEFINE VAR cOKButLst   AS CHARACTER NO-UNDO.
DEF VAR cOKButNavn AS CHAR NO-UNDO.
DEFINE VAR lOK         AS LOGICAL   NO-UNDO.
DEFINE VAR cReturn     AS CHARACTER NO-UNDO.

ASSIGN
    ibutNr = 10
    .

RUN  getOvButLst.p (iButNr, '', OUTPUT cOKButLst, OUTPUT cOKButNavn, OUTPUT lOk, OUTPUT cReturn).

MESSAGE cOkButLst SKIP
    cOkbutNavn
    VIEW-AS ALERT-BOX INFO BUTTONS OK.
