DISPLAY 'PkSdlHode' WITH FRAME A.
PAUSE 0.
FOR EACH PKSdlHode:
    DELETE PKSdlHode.
END.
FOR EACH PKSDLLinje:
    DELETE PkSDLLinje.
END.
DISPLAY 'PkSdlPris' WITH FRAME A.
PAUSE 0.
FOR EACH PkSdlPris:
    DELETE PkSdlPris.
END.

DISPLAY 'PkSdlMottak' WITH FRAME A.
PAUSE 0.
FOR EACH PkSdlMottak:
    DELETE PkSdlMottak.
END.

DISPLAY 'VPIFilHode' WITH FRAME A.
PAUSE 0.
FOR EACH VPIFilHode: DELETE VPIFilHode. END.
DISPLAY 'VPIFilLinje' WITH FRAME A.
PAUSE 0.
FOR EACH VPIFilLinje: DELETE VPIFilLinje. END.
DISPLAY 'VPIFilLogg' WITH FRAME A.
PAUSE 0.
FOR EACH VPIFilLogg: DELETE VPIFilLogg. END.

