DEF VAR cEAN AS CHAR FORMAT "x(30)" NO-UNDO.
DEF VAR cTekst AS CHAR FORMAT "x(30)" NO-UNDO.

ASSIGN 
    cEAN = '0000000006875'.

RUN bibl_chkean.p (INPUT-OUTPUT cEAN).

MESSAGE cEAN SKIP
    RETURN-VALUE
    VIEW-AS ALERT-BOX INFO BUTTONS OK.
