DEFINE VARIABLE hServer AS HANDLE NO-UNDO.

CREATE SERVER hServer.
hServer:CONNECT("-H LAPTOP-CENEE05L -S 3090 -AppService asPRS -DirectConnect").

MESSAGE hServer:CONNECTED()
    VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
