DEF INPUT  PARAM icKampanjeEierRowid    AS CHAR NO-UNDO.
DEF INPUT  PARAM icFields     AS CHAR NO-UNDO.
DEF INPUT  PARAM icValues     AS CHAR NO-UNDO.
DEF INPUT  PARAM icSessionId  AS CHAR NO-UNDO.
DEF OUTPUT PARAM ocReturn     AS CHAR NO-UNDO.


