
DEFINE INPUT PARAMETER cFirstName AS CHAR NO-UNDO. 
DEFINE INPUT PARAMETER fld-lastname AS CHAR NO-UNDO. 
DEFINE INPUT PARAMETER fld-address AS CHAR NO-UNDO. 
DEFINE INPUT PARAMETER fld-zip AS CHAR NO-UNDO. 
DEFINE INPUT PARAMETER fld-city AS CHAR NO-UNDO. 
DEFINE INPUT PARAMETER fld-email AS CHAR NO-UNDO. 
DEFINE INPUT PARAMETER fld-phone AS CHAR NO-UNDO. 
DEFINE INPUT PARAMETER fld-bdate AS CHAR NO-UNDO. 
DEFINE INPUT PARAMETER fld-sex AS CHAR NO-UNDO. 
DEFINE OUTPUT PARAMETER oStatus AS LOGICAL NO-UNDO. 


oStatus = TRUE. 
RETURN. 
