copy q:\appdir\skotex\ocx\*.ocx c:\windows
c:\windows\system\regsvr32 c:\windows\comctl32.ocx
c:\windows\system\regsvr32 c:\windows\msflxgrd.ocx
c:\windows\system\regsvr32 c:\windows\oik32.ocx
c:\windows\system\regsvr32 c:\windows\iemenu.ocx
c:\windows\system\regsvr32 c:\windows\mschart.ocx
c:\windows\system\regsvr32 c:\windows\vsflex6d.ocx
rem copy q:\ocx\skotex32.lnk c:\windows\skrivbord

