TRIGGER PROCEDURE FOR DELETE OF PrisKo.

OUTPUT TO value('log\prisko.log').
PUT UNFORMATTED  'Gurre var her' SKIP.
PUT UNFORMATTED 
  PROGRAM-NAME(1) SKIP
  PROGRAM-NAME(2) SKIP
  PROGRAM-NAME(3) SKIP
  PROGRAM-NAME(4) SKIP
  PROGRAM-NAME(5) SKIP
  PROGRAM-NAME(6) SKIP
  PROGRAM-NAME(7) SKIP
  PROGRAM-NAME(8) SKIP
  PROGRAM-NAME(9) SKIP
  PROGRAM-NAME(10) SKIP
  STRING(NOW)
  . 
OUTPUT CLOSE.

