DEFINE OUTPUT PARAMETER dSIETransId LIKE SIETrans.SIETransId  NO-UNDO.

FIND LAST SIETrans NO-LOCK USE-INDEX SIETransId NO-ERROR.

IF AVAILABLE SIETrans
  THEN dSIETransId = SIETrans.SIETransId + 1.
  ELSE dSIETransId = 1.
